[package]
name = "arythmitical/limitedtable"
version = "1.0.0"
description = "Constructor of tables with size limits. Useful for interpreters, VMs and much more."
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
