[package]
name = "arythmitical/limitedtable"
version = "1.1.4"
description = "Constructor of Luau tables with size limits. Useful for interpreters, VMs and much more."
registry = "https://github.com/UpliftGames/wally-index"
license = "MIT"
realm = "shared"
